name: Pull Request WorkFlow

on:
  pull_request:
    branches:
      - main
      - master
      - staging
  push:
    branches:
      - '**'

jobs:
  app-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
      - name: Copy .env
        run: cp .env.example .env
      - name: Install Composer Dependencies
        run: composer install
      - name: Generate key
        run: php artisan key:generate
      - name: Execute tests (Unit and Feature tests) using PHP Unit
        run: ./vendor/bin/phpunit
